cmake_minimum_required(VERSION 3.5)
project(mspace_forest_plant)
set(CMAKE_CXX_STANDARD 17)
find_package(gazebo REQUIRED)
find_package(catkin REQUIRED COMPONENTS roscpp nav_msgs sensor_msgs)
include_directories(${GAZEBO_INCLUDE_DIRS} ${catkin_INCLUDE_DIRS})
link_directories(${GAZEBO_LIBRARY_DIRS})
add_library(mspace_forest_plant SHARED forest_plant.cpp)
target_link_libraries(mspace_forest_plant ${GAZEBO_LIBRARIES} ${catkin_LIBRARIES})
