common:
    lid_topic:  "/lidar_points"
    imu_topic:  "/lidar_imu"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms

preprocess:
    lidar_type: 5                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 4 for simulation, 5 for Hesai JT128
    scan_line: 128
    scan_rate: 10                # scan rate, unit: Hz
    timestamp_unit: 0            # relative offset unit: 0=second -> curvature in ms
    blind: 1

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0005
    b_gyr_cov: 0.0005
    fov_degree:    180
    det_range:     100.0
    extrinsic_est_en:  false
    extrinsic_T: [ 0, 0, 0.1]
    extrinsic_R: [ 1, 0, 0, 
                   0, 1, 0, 
                   0, 0, 1]

publish:
    path_en:  true
    scan_publish_en:  true
    dense_publish_en: true
    scan_bodyframe_pub_en: true

pcd_save:
    pcd_save_en: false
    interval: -1